task0

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -2,9 +2,11 @@
 # Bash script that transfers a file from our client to a server:
 
 # check if parameter are 4 or less and display a message if less than 3 params
-if [ "$#" -lt 4 ]; then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit 1
+if [ "$#" -lt 4 ]
+then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
 
 # assign parameter to variables
 transfer_file="$1"
@@ -14,4 +16,10 @@ username="$4"
 
 # use scp; to transfer file to server through ssh
 scp -o StrictHostKeyChecking=no -i "$private_key" "$transfer_file" "$username"@"$server_ip"
+# rechecking if the transfer file was successful
+if [ $? -eq 0 ]
+then 
+  echo "FILE TRANSFER WAS SUCCESSFUL"
+else
+  echo "FILE TRANSFER FAILED"
 fi
